name: Java Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/*.kt'
      - '**/*.java'
      - '**/build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - '.github/workflows/java-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.kt'
      - '**/*.java'
      - '**/build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - '.github/workflows/java-tests.yml'

jobs:
  test:
    name: Test with Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java: ['17', '21']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: |
          ./gradlew test \
            :parkflow-common:test \
            :parkflow-entry-exit:test \
            --no-daemon || {
              echo "::group::Test Logs"
              ./gradlew --no-daemon test --debug
              echo "::endgroup::"
              exit 1
            }

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-java-${{ matrix.java }}
          path: |
            **/build/reports/tests/
            **/build/test-results/
          retention-days: 7

  report:
    name: Process Test Results
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          pattern: test-results-java-*
          merge-multiple: true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          detailed_summary: true
          include_passed: true
