name: Test Entry Service

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'parkflow-entry-exit/**'
      - 'parkflow-common/**'
      - '.github/workflows/test-entry-service.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'parkflow-entry-exit/**'
      - 'parkflow-common/**'
      - '.github/workflows/test-entry-service.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      PYTHON_VERSION: '3.11'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          # Install system dependencies first
          sudo apt-get update
          sudo apt-get install -y kafkacat jq
          # Install Python and Java dependencies
          make venv deps

      - name: Start Infrastructure
        run: |
          docker compose pull
          make start
          sleep 10  # Give services time to start
          make status

      - name: Run Entry Service Tests
        run: |
          ./gradlew :parkflow-entry-exit:test || {
            echo "::group::Service Logs"
            make logs
            echo "::endgroup::"
            exit 1
          }

      - name: Run Integration Tests
        run: |
          ./gradlew :parkflow-entry-exit:integrationTest || {
            echo "::group::Integration Test Logs"
            make logs
            echo "::endgroup::"
            exit 1
          }

      - name: Test Event Flow
        run: |
          make simulate EVENTS=5 DELAY=100 || {
            echo "::group::Event Flow Logs"
            make logs
            echo "::endgroup::"
            exit 1
          }
          sleep 2

      - name: Cleanup
        if: always()
        run: |
          make clean
          docker compose down -v

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './parkflow-entry-exit'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
